export const SET_NOTIFICATIONS = "SET_NOTIFICATIONS";
export const REMOVE_NOTIFICATIONS = "REMOVE_NOTIFICATIONS";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const USER_LOADED = "USER_LOADED";
export const AUTH_TOKEN_ERROR = "AUTH_TOKEN_ERROR";

export const SET_INVALID_ENTRIES = "SET_INVALID_ENTRIES";
export const SET_VALID_ENTRIES = "SET_VALID_ENTRIES";
export const CLEAR_ENTRIES = "CLEAR_ENTRIES";

export const EVENTS_STORE = "EVENTS_STORE";
export const EVENTS_GET = "EVENTS_GET";
export const EVENTS_ERROR = "EVENTS_ERROR";
export const EVENT_VOTE = "EVENT_VOTE";
